{
 "title": "kubernetes events",
 "description": "Kubernetes Events",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter", "query": "reason != 'OOMKilling'" },
   {
    "name": "cluster_name",
    "label": "集群",
    "query": "SELECT DISTINCT cluster FROM k8s_db.t_kubernetes_events_info WHERE  cluster != '' AND $filter"
   },
   {
    "name": "kind",
    "label": "kind",
    "query": "SELECT DISTINCT involvedObject_kind FROM k8s_db.t_kubernetes_events_info WHERE  \n1=1 AND $filter \n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name) \nlimit 1000"
   },
   { "name": "type", "label": "type", "query": "Normal, Warning" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "SELECT DISTINCT involvedObject_namespace FROM k8s_db.t_kubernetes_events_info WHERE  1=1 AND $filter \n\n\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\n$conditionalTest(AND type IN (${type:singlequote}), $type)\nlimit 1000\n"
   },
   {
    "name": "host",
    "query": "SELECT DISTINCT source_host FROM k8s_db.t_kubernetes_events_info WHERE  \n1=1 AND $filter \n\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\n$conditionalTest(AND type IN (${type:singlequote}), $type)\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\nlimit 1000\n"
   },
   {
    "name": "name",
    "query": "SELECT DISTINCT involvedObject_name FROM k8s_db.t_kubernetes_events_info WHERE  1=1\n AND $filter \n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\n$conditionalTest(AND type IN (${type:singlequote}), $type)\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\nlimit 1000\n"
   },
   {
    "name": "reason",
    "label": "reason",
    "query": "SELECT DISTINCT reason FROM k8s_db.t_kubernetes_events_info WHERE  1=1\n AND $filter \n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\n$conditionalTest(AND type IN (${type:singlequote}), $type)\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\nlimit 10000"
   },
   { "name": "search", "label": "搜索(name/message)" }
  ]
 },
 "panels": [
  { "title": "重要事件", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ConntrackFull",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE \r\n$timeFilter AND $filter\r\nAND\r\nreason='ConntrackFull'\r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT (intDiv(toUInt32(eventTime), 1) * 1) * 1000 as t, count() FROM k8s_db.t_kubernetes_events_info WHERE \r\neventTime >= toDateTime(1729062524) AND eventTime <= toDateTime(1729062824)\r\nAND\r\nreason='ConntrackFull')\r\n AND cluster IN ('pre-cluster') \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "SystemOOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE \r\n$timeFilter AND $filter\r\nAND\r\nmatch(reason, 'SystemOOM')\r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT (intDiv(toUInt32(eventTime), 1) * 1) * 1000 as t, count() FROM k8s_db.t_kubernetes_events_info WHERE \r\neventTime >= toDateTime(1729061354) AND eventTime <= toDateTime(1729062254)\r\nAND\r\nmatch(reason, 'SystemOOM')\r\nAND\r\nmatch(cluster, 'pre-cluster,k8s-yunying')\r\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "Rebooted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE \r\n$timeFilter AND $filter\r\nAND\r\nreason='Rebooted' \r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT (intDiv(toUInt32(eventTime), 1) * 1) * 1000 as t, count() FROM k8s_db.t_kubernetes_events_info WHERE \r\neventTime >= toDateTime(1729062538) AND eventTime <= toDateTime(1729062838)\r\nAND\r\nreason='Rebooted'\r\n AND cluster IN ('pre-cluster') \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "Node*-节点不稳定",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE \r\n$timeFilter AND $filter\r\nAND \r\nreason IN ('NodeHasSufficientDisk',\r\n'NodeReady',\r\n'NodeNotReady',\r\n'NodeHasSufficientPID',\r\n'NodeHasNoDiskPressure',\r\n'NodeAllocatableEnforced')\r\n\r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT (intDiv(toUInt32(eventTime), 300) * 300) * 1000 as t, count() FROM k8s_db.t_kubernetes_events_info WHERE \r\neventTime >= toDateTime(1728877498) AND eventTime <= toDateTime(1729223098) AND reason != 'OOMKilling'\r\nAND \r\nreason IN ('NodeHasSufficientDisk',\r\n'NodeReady',\r\n'NodeNotReady',\r\n'NodeHasSufficientPID',\r\n'NodeHasNoDiskPressure',\r\n'NodeAllocatableEnforced')\r\n\r\n \r\n \r\n AND type IN ('Normal','Warning') \r\n \r\n \r\n \r\n \r\n \r\n\r\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "BackOff-容器Crash",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE \r\n$timeFilter AND $filter\r\nAND\r\nreason IN ('BackOff','CrashLoopBackOff') \r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT (intDiv(toUInt32(eventTime), 120) * 120) * 1000 as t, count() FROM k8s_db.t_kubernetes_events_info WHERE \r\neventTime >= toDateTime(1728963789) AND eventTime <= toDateTime(1729136589) AND reason != 'OOMKilling'\r\nAND\r\nreason IN ('BackOff','CrashLoopBackOff')\r\n \r\n \r\n AND type IN ('Normal','Warning') \r\n \r\n \r\n \r\n \r\n \r\n\r\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "FailedScheduling-调度失败",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE \r\n$timeFilter AND $filter\r\nAND\r\nreason='FailedScheduling' \r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT (intDiv(toUInt32(eventTime), 1) * 1) * 1000 as t, count() FROM k8s_db.t_kubernetes_events_info WHERE \r\neventTime >= toDateTime(1729062596) AND eventTime <= toDateTime(1729062896)\r\nAND\r\nmreason='FailedScheduling' \r\n AND cluster IN ('pre-cluster') \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "FailedMount-卷挂载失败",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE \r\n$timeFilter AND $filter\r\nAND \r\nreason='FailedMount' \r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT (intDiv(toUInt32(eventTime), 1) * 1) * 1000 as t, count() FROM k8s_db.t_kubernetes_events_info WHERE \r\neventTime >= toDateTime(1729062582) AND eventTime <= toDateTime(1729062882)\r\nAND \r\nreason'FailedMount' \r\n AND cluster IN ('pre-cluster') \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "Evictied-驱逐",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE \r\n$timeFilter AND $filter\r\nAND\r\nreason IN ('TaintManagerEviction', 'Evictied') \r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT (intDiv(toUInt32(eventTime), 120) * 120) * 1000 as t, count() FROM k8s_db.t_kubernetes_events_info WHERE \r\neventTime >= toDateTime(1728963749) AND eventTime <= toDateTime(1729136549) AND reason != 'OOMKilling'\r\nAND\r\nreason IN ('TaintManagerEviction', 'Evictie') \r\n \r\n \r\n AND type IN ('Normal','Warning') \r\n \r\n \r\n \r\n \r\n \r\n\r\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "Failed-镜像拉取失败",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE \r\n$timeFilter AND $filter\r\nAND\r\nreason='Failed' \r\nAND\r\nmatch(message, '.*ImagePullBackOff.*')\r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT (intDiv(toUInt32(eventTime), 1) * 1) * 1000 as t, count() FROM k8s_db.t_kubernetes_events_info WHERE \r\neventTime >= toDateTime(1729062608) AND eventTime <= toDateTime(1729062908)\r\nAND\r\nreason'Failed' \r\nAND\r\nmatch(message, '.*ImagePullBackOff.*')\r\n AND cluster IN ('pre-cluster') \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kubernetes Events",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    $timeSeries as t,\r\n    reason,\r\n    count()\r\nFROM $table\r\nWHERE\r\n    $timeFilter AND $filter\r\n    $conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n    $conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n    $conditionalTest(AND type IN (${type:singlequote}), $type)\r\n    $conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n    $conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n    $conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n    $conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n    $conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\nGROUP BY\r\n t,\r\n reason",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT\r\n    (intDiv(toUInt32(eventTime), 60) * 60) * 1000 as t,\r\n    reason,\r\n    count()\r\nFROM k8s_db.t_kubernetes_events_info\r\nWHERE\r\n    eventTime >= toDateTime(1728978170) AND eventTime <= toDateTime(1729064570)\r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\nGROUP BY\r\n t,\r\n reason",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "reason",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    count() as none,\r\n    `reason` as kind\r\nFROM $table\r\nWHERE\r\n    $timeFilter AND $filter\r\n    $conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n    $conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n    $conditionalTest(AND type IN (${type:singlequote}), $type)\r\n    $conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n    $conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n    $conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n    $conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n    $conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n\r\nGROUP BY\r\n kind\r\nORDER BY\r\n none",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT\r\n    count() as none,\r\n    `reason` as kind\r\nFROM k8s_db.t_kubernetes_events_info\r\nWHERE\r\n    eventTime >= toDateTime(1728978109) AND eventTime <= toDateTime(1729064509)\r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n\r\nGROUP BY\r\n kind\r\nORDER BY\r\n none",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "kind",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    count() as c,\r\n    `involvedObject_kind` as kind\r\nFROM $table\r\nWHERE\r\n    $timeFilter AND $filter\r\n    $conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n    $conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n    $conditionalTest(AND type IN (${type:singlequote}), $type)\r\n    $conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n    $conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n    $conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n    $conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n    $conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n\r\n\r\nGROUP BY\r\n kind\r\nORDER BY\r\n c",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT\r\n    count() as c,\r\n    `involvedObject_kind` as kind\r\nFROM k8s_db.t_kubernetes_events_info\r\nWHERE\r\n    eventTime >= toDateTime(1728978098) AND eventTime <= toDateTime(1729064498)\r\n     \r\n     \r\n     \r\n     \r\n     AND source_host IN ('10.11.154.243') \r\n     \r\n     \r\n     \r\n\r\n\r\nGROUP BY\r\n kind\r\nORDER BY\r\n c",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    count() as c,\r\n    `type` as kind\r\nFROM $table\r\nWHERE\r\n    $timeFilter AND $filter\r\n    $conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n    $conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n    $conditionalTest(AND type IN (${type:singlequote}), $type)\r\n    $conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n    $conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n    $conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n    $conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n    $conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n\r\nGROUP BY\r\n kind\r\nORDER BY\r\n c",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT\r\n    count() as c,\r\n    `type` as kind\r\nFROM k8s_db.t_kubernetes_events_info\r\nWHERE\r\n    eventTime >= toDateTime(1728978070) AND eventTime <= toDateTime(1729064470)\r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n\r\nGROUP BY\r\n kind\r\nORDER BY\r\n c",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "namespace",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    count() as none,\r\n    `involvedObject_namespace` as kind\r\nFROM $table\r\nWHERE\r\n    $timeFilter AND $filter\r\n    $conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n    $conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n    $conditionalTest(AND type IN (${type:singlequote}), $type)\r\n    $conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n    $conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n    $conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n    $conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n    $conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n\r\nGROUP BY\r\n kind\r\nORDER BY\r\n none",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT\r\n    count() as none,\r\n    `involvedObject_namespace` as kind\r\nFROM k8s_db.t_kubernetes_events_info\r\nWHERE\r\n    eventTime >= toDateTime(1728978092) AND eventTime <= toDateTime(1729064492)\r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n\r\nGROUP BY\r\n kind\r\nORDER BY\r\n none",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "component",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    count() as c,\r\n    `source_component` as kind\r\nFROM $table\r\nWHERE\r\n    $timeFilter AND $filter\r\n    $conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n    $conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n    $conditionalTest(AND type IN (${type:singlequote}), $type)\r\n    $conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n    $conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n    $conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n    $conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n    $conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\nGROUP BY\r\n kind\r\nORDER BY\r\n c",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT\r\n    count() as c,\r\n    `source_component` as kind\r\nFROM k8s_db.t_kubernetes_events_info\r\nWHERE\r\n    eventTime >= toDateTime(1728978084) AND eventTime <= toDateTime(1729064484)\r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\nGROUP BY\r\n kind\r\nORDER BY\r\n c",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "host",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    count() as none,\r\n    `source_host` as kind\r\nFROM $table\r\nWHERE\r\n    $timeFilter AND $filter\r\n    $conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n    $conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n    $conditionalTest(AND type IN (${type:singlequote}), $type)\r\n    $conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n    $conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n    $conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n    $conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n    $conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\n\r\n\r\nGROUP BY\r\n kind\r\nORDER BY\r\n none",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT\r\n    count() as none,\r\n    `source_host` as kind\r\nFROM k8s_db.t_kubernetes_events_info\r\nWHERE\r\n    eventTime >= toDateTime(1728978117) AND eventTime <= toDateTime(1729064517)\r\n     \r\n     \r\n     \r\n     \r\n     AND source_host IN ('10.11.154.243') \r\n     \r\n     \r\n     \r\n\r\nGROUP BY\r\n kind\r\nORDER BY\r\n none",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "时间线",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ALL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT \r\n$timeSeries as t, \r\n`type`as k, \r\ncount() \r\nFROM \r\n$table \r\nWHERE \r\n$timeFilter AND $filter \r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\nGROUP BY \r\nt,k \r\nORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT \r\n(intDiv(toUInt32(eventTime), 30) * 30) * 1000 as t, \r\n`type`as k, \r\ncount() \r\nFROM \r\nk8s_db.t_kubernetes_events_info \r\nWHERE \r\neventTime >= toDateTime(1729059426) AND eventTime <= toDateTime(1729122798) AND reason != 'OOMKilling' \r\n \r\n AND involvedObject_kind IN ('ETCDSnapshotFile') \r\n\r\n \r\n \r\n \r\n \r\n \r\nGROUP BY \r\nt,k \r\nORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT \r\n$timeSeries as t, \r\ncount() as all_warnings\r\nFROM \r\n$table\r\nWHERE \r\n$timeFilter AND $filter \r\nAND\r\ntype='Warning'\r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\nGROUP BY \r\nt\r\nORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT \r\n(intDiv(toUInt32(eventTime), 1) * 1) * 1000 as t, \r\ncount() as all_warning\r\nFROM \r\nk8s_db.t_kubernetes_events_info\r\nWHERE \r\neventTime >= toDateTime(1729064288) AND eventTime <= toDateTime(1729066088) \r\nAND\r\ntype='Warning'\r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\nGROUP BY \r\nt\r\nORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    },
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT \r\n$timeSeries as t,\r\nreason,\r\ncount()\r\nFROM \r\n$table\r\nWHERE \r\n$timeFilter AND $filter \r\nAND\r\ntype='Warning'\r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\nGROUP BY \r\nt, reason\r\nORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT (intDiv(toUInt32(eventTime), 1) * 1) * 1000 as t, count() FROM k8s_db.t_kubernetes_events_info WHERE eventTime >= toDateTime(1729064143) AND eventTime <= toDateTime(1729065943) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "Reason",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT \r\n$timeSeries as t, \r\nreason,\r\ncount() \r\nFROM \r\n$table \r\nWHERE \r\n$timeFilter AND $filter \r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\nGROUP BY \r\nt,reason \r\nORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT \r\n(intDiv(toUInt32(eventTime), 30) * 30) * 1000 as t, \r\nreason,\r\ncount() \r\nFROM \r\nk8s_db.t_kubernetes_events_info \r\nWHERE \r\neventTime >= toDateTime(1729059426) AND eventTime <= toDateTime(1729122798) AND reason != 'OOMKilling' \r\n \r\n AND involvedObject_kind IN ('ETCDSnapshotFile') \r\n\r\n \r\n \r\n \r\n \r\n \r\nGROUP BY \r\nt,reason \r\nORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "Cluster Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT \r\n$timeSeries as t, \r\ncluster,\r\ncount() \r\nFROM \r\n$table \r\nWHERE \r\n$timeFilter AND $filter \r\n$conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n$conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n$conditionalTest(AND type IN (${type:singlequote}), $type)\r\n$conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n$conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n$conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n$conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n$conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\nGROUP BY \r\nt,cluster\r\nORDER BY t",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT \r\n(intDiv(toUInt32(eventTime), 30) * 30) * 1000 as t, \r\ncluster,\r\ncount() \r\nFROM \r\nk8s_db.t_kubernetes_events_info \r\nWHERE \r\neventTime >= toDateTime(1729059426) AND eventTime <= toDateTime(1729122798) AND reason != 'OOMKilling' \r\n \r\n AND involvedObject_kind IN ('ETCDSnapshotFile') \r\n\r\n \r\n \r\n \r\n \r\n \r\nGROUP BY \r\nt,cluster\r\nORDER BY t",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  },
  {
   "title": "事件",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "database": "k8s_db",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter AND $filter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    eventTime as time,\r\n    cluster,\r\n    source_component as component,\r\n    source_host as host,\r\n    involvedObject_kind as kind,\r\n    involvedObject_namespace as ns,\r\n    involvedObject_name as name,\r\n    type,\r\n    reason,\r\n    message,\r\n    `count`\r\nFROM $table\r\nWHERE\r\n    $timeFilter\r\n    $conditionalTest(AND cluster IN (${cluster_name:singlequote}), $cluster_name)\r\n    $conditionalTest(AND involvedObject_kind IN (${kind:singlequote}), $kind)\r\n    $conditionalTest(AND type IN (${type:singlequote}), $type)\r\n    $conditionalTest(AND involvedObject_namespace IN (${namespace:singlequote}), $namespace)\r\n    $conditionalTest(AND source_host IN (${host:singlequote}), $host)\r\n    $conditionalTest(AND involvedObject_name IN (${name:singlequote}), $name)\r\n    $conditionalTest(AND reason IN (${reason:singlequote}), $reason)\r\n    $conditionalTest(AND (match(involvedObject_name, '.*${search:raw}.*') OR match(message, '.*${search:raw}.*')), $search)\r\nORDER BY\r\n    time DESC",
     "rawQuery": "/* grafana dashboard=kubernetes events, user=1 */\nSELECT\r\n    eventTime as time,\r\n    cluster,\r\n    source_component as component,\r\n    source_host as host,\r\n    involvedObject_kind as kind,\r\n    involvedObject_namespace as ns,\r\n    involvedObject_name as name,\r\n    type,\r\n    reason,\r\n    message,\r\n    `count`\r\nFROM k8s_db.t_kubernetes_events_info\r\nWHERE\r\n    eventTime >= toDateTime(1729131655) AND eventTime <= toDateTime(1729135255) \r\n     \r\n     \r\n     AND type IN ('Warning') \r\n     \r\n     \r\n     \r\n     \r\n     \r\nORDER BY\r\n    time DESC",
     "round": "0s",
     "table": "t_kubernetes_events_info"
    }
   ]
  }
 ]
}